version: '3'
services:
  wp:
    image: wordpress:5.7.1
    volumes:
      - ./src:/var/www/html/wp-content/plugins/wp-custompost-lib
      - ./themes:/var/www/html/wp-content/themes
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=sample
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG=1
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: password
      #  pma:
      #    image: phpmyadmin/phpmyadmin
      #    ports:
      #      - 8080:80
      #    depends_on:
      #      - db
      #    environment:
      #      PMA_HOST: db
